const express = require("express");
const router = express.Router();
const databaseController = require("../app/controllers/DatabaseController");
router.get("/getfullname", databaseController.getFullname);
router.get("/getWarning", databaseController.getWarning);
router.get("/getAlarmRange", databaseController.getAlarmRange);
router.post("/setAlarmValueNode1", databaseController.setAlarmValueNode1);
router.post("/setAlarmValueNode2", databaseController.setAlarmValueNode2);
router.get("/getChartDataNode1", databaseController.getChartDataNode1);
router.get("/getChartDataNode2", databaseController.getChartDataNode2);
router.get("/setStart", databaseController.setStart);
router.get("/setStop", databaseController.setStop);
router.get("/setReset", databaseController.setReset);
router.get("/getLightStatus", databaseController.getLightStatus);
router.post("/setAlarmStatus", databaseController.setAlarmStatus);
router.get("/getAlarmTable", databaseController.getAlarmTable);
router.get("/getUsers", databaseController.getUsers);
router.post("/editUsername", databaseController.editUsername);
router.post("/editPassword", databaseController.editPassword);
router.post("/editFirstName", databaseController.editFirstName);
router.post("/editLastName", databaseController.editLastName);
router.post("/editRole", databaseController.editRole);
router.post("/createUser", databaseController.createUser);
router.post("/deleteUser", databaseController.deleteUser);

module.exports = router;
