const express = require("express");
const router = express.Router();
const databaseController = require("../app/controllers/DatabaseController");
router.get("/getfullname", databaseController.getFullname);
router.get("/getWarning", databaseController.getWarning);
router.get("/getAlarmRange", databaseController.getAlarmRange);
router.post("/setAlarmValue", databaseController.setAlarmValue);
router.get("/getChartData", databaseController.getChartData);
router.get("/setStart", databaseController.setStart);
router.get("/setStop", databaseController.setStop);
router.get("/setReset", databaseController.setReset);
router.get("/getLightStatus", databaseController.getLightStatus);
router.post("/setAlarmStatus", databaseController.setAlarmStatus);
router.get("/getAlarmTable", databaseController.getAlarmTable);
module.exports = router;
